name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test XLS
      run: go test -v ./xls

    - name: Test XLSX
      run: go test -v ./xlsx

    - name: Test CommonXL
      run: go test -v ./commonxl
